<<<<<<< HEAD
name: Deploy Vite Projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust this based on your Node.js version requirements

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Shared Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftpupload.net
          username: ezyro_36663805
          password: 48e2dbc956
          local-dir: build/ # Adjust this path based on your build output directory
          server-dir: htdocs/ # Adjust this based on your hosting provider's directory structure
=======
name: Deploy Vite Projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust this based on your Node.js version requirements

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Shared Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftpupload.net
          username: ezyro_36663805
          password: 48e2dbc956
          local-dir: build/ # Adjust this path based on your build output directory
          server-dir: htdocs/ # Adjust this based on your hosting provider's directory structure
>>>>>>> a602725741c34e2b6d8ab9f3cbbab6e55752670d
